[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/api/news"
  to   = "/.netlify/functions/api-news"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
