#!/usr/bin/env python3
"""
Code Architect Agent — Designs and scaffolds new bots and agents.
Give it a requirement in plain English and it outputs production-ready Python.

Usage:
  python agents/code_architect_agent.py "Build a bot that scrapes job postings from Indeed"
  python agents/code_architect_agent.py --type agent "Build a competitive intelligence agent"

Output: Complete Python file with:
  - Proper imports and error handling
  - Logging and Pushover notifications
  - Supabase persistence
  - run() function
  - if __name__ == "__main__" block
"""
import os, sys, json, logging
from datetime import datetime
sys.path.insert(0, ".")
try:
    from agents.claude_core import claude
except:
    def claude(s,u,**k): return ""

import urllib.request

log = logging.getLogger(__name__)

GH_TOKEN = os.environ.get("GH_PAT") or os.environ.get("GITHUB_TOKEN","")
REPO     = os.environ.get("GITHUB_REPOSITORY","nyspotlightreport/sct-agency-bots")
ANTHROPIC = os.environ.get("ANTHROPIC_API_KEY","")

BOT_TEMPLATE_PROMPT = """You are a senior Python engineer building automation bots for an AI agency system.
Build a complete, production-ready Python bot/agent based on the requirement.

SYSTEM CONTEXT:
- Python 3.11+ | No external dependencies unless standard lib or requests
- Supabase for persistence (via supabase_request helper)
- Claude AI via agents.claude_core (claude() and claude_json() functions)
- Pushover for notifications (PUSHOVER_API_KEY, PUSHOVER_USER_KEY env vars)
- GitHub Actions runner — must complete in <10 minutes
- All env vars via os.environ.get() with graceful fallback

REQUIRED STRUCTURE:
1. Module docstring (what it does, when it runs, what it outputs)
2. Imports (only os, sys, json, logging, datetime, urllib — no pip)
3. Logger setup
4. Config from env vars
5. Core functions (well-named, single responsibility)
6. run() function — main entry point, returns dict with metrics
7. if __name__ == "__main__": block with logging setup + run()

QUALITY REQUIREMENTS:
- Every function has a docstring
- All external calls wrapped in try/except
- Graceful degradation if API keys missing
- Log progress at INFO level
- Return useful metrics from run()
- Code must be immediately runnable

Generate the complete, runnable Python file. No explanation text outside the code."""

def architect_bot(requirement: str, output_type: str = "bot") -> str:
    """Generate a complete bot/agent from a plain English requirement."""
    prefix = "bots" if output_type == "bot" else "agents"
    
    # Extract a good filename from the requirement
    name_prompt = f'Given requirement: "{requirement}" — generate a snake_case Python filename (no extension) for a {"bot" if output_type == "bot" else "agent"}. Just the filename, nothing else.'
    filename = claude("Generate Python filename only.", name_prompt, max_tokens=20)
    filename = filename.strip().strip('"').replace(" ","_").replace("-","_").lower() or "new_bot"
    if not filename.endswith("_bot") and output_type == "bot":
        filename += "_bot"
    if not filename.endswith("_agent") and output_type == "agent":
        filename += "_agent"
    
    # Generate the full code
    code = claude(
        BOT_TEMPLATE_PROMPT,
        f"REQUIREMENT: {requirement}\nOUTPUT TYPE: {output_type}\nFILENAME: {filename}.py\n\nGenerate the complete Python code:",
        max_tokens=2000
    )
    
    if not code: return ""
    
    # Clean up if Claude added markdown fences
    if "```python" in code: code = code.split("```python",1)[1].split("```",1)[0]
    elif "```" in code:     code = code.split("```",1)[1].split("```",1)[0]
    
    return code.strip(), filename, prefix

def push_to_repo(code: str, path: str) -> bool:
    """Push generated code to GitHub."""
    import base64
    try:
        r = urllib.request.Request(
            f"https://api.github.com/repos/{REPO}/contents/{path}",
            headers={"Authorization":f"token {GH_TOKEN}","Accept":"application/vnd.github+json"}
        )
        with urllib.request.urlopen(r,timeout=10) as res:
            existing = json.loads(res.read())
            sha = existing.get("sha","")
    except: sha = ""
    
    payload = {"message":f"feat: Auto-generated by Code Architect — {path.split('/')[-1]}",
               "content": __import__("base64").b64encode(code.encode()).decode()}
    if sha: payload["sha"] = sha
    
    req = urllib.request.Request(
        f"https://api.github.com/repos/{REPO}/contents/{path}",
        data=json.dumps(payload).encode(),
        headers={"Authorization":f"token {GH_TOKEN}","Content-Type":"application/json","Accept":"application/vnd.github+json"},
        method="PUT"
    )
    try:
        with urllib.request.urlopen(req,timeout=20) as r:
            return r.status in [200,201]
    except Exception as e:
        log.error(f"Push failed: {e}")
        return False

def run():
    """Architect mode: read requirements from ARCHITECT_REQUIREMENT env var."""
    requirement = os.environ.get("ARCHITECT_REQUIREMENT","")
    output_type = os.environ.get("ARCHITECT_TYPE","bot")
    
    if not requirement:
        log.info("No ARCHITECT_REQUIREMENT set — running in demo mode")
        requirement = "Build a bot that monitors competitor pricing and alerts on changes"
        output_type = "bot"
    
    log.info(f"Architecting: {requirement[:80]}...")
    result = architect_bot(requirement, output_type)
    
    if not result:
        log.error("Code generation failed")
        return {"status":"failed"}
    
    code, filename, prefix = result
    path = f"{prefix}/{filename}.py"
    
    log.info(f"Generated {len(code)} chars → {path}")
    
    if GH_TOKEN:
        pushed = push_to_repo(code, path)
        log.info(f"Pushed to repo: {pushed}")
        return {"status":"success","path":path,"size":len(code),"pushed":pushed}
    else:
        print("\n" + "="*60)
        print(f"GENERATED: {path}")
        print("="*60)
        print(code[:500] + "..." if len(code)>500 else code)
        return {"status":"generated","path":path,"size":len(code),"pushed":False}

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [Architect] %(message)s")
    if len(sys.argv) > 1:
        req  = " ".join(sys.argv[1:])
        otype = "agent" if "--type agent" in req else "bot"
        req  = req.replace("--type agent","").strip()
        result = architect_bot(req, otype)
        if result:
            code, fname, prefix = result
            print(code)
    else:
        run()
